### ISSUE TITLE
Chrome Extension keeps re-installing itself

### ISSUE THREAD

**Issue by nicknormal** [kenotron/sourcekit#122]
About 3-5 times a day the Extension will remind a Chrome user they need to re-enable permissions, even if the extension has been deleted and removed from the Chrome account.

**Comment by kenotron** [comment]
I don't have this experience. I really do not know how to reproduce this?

**Comment by kenotron** [comment]
https://developer.chrome.com/extensions/permission_warnings

According to this, it is requesting new perms when I updated the ext. I did recently update ONCE. I expect it to do that once. The rest I would only expect to happen maybe across multiple machines...

Can you describe the issue in more details? What steps did you do to reproduce this?

**Comment by nicknormal** [comment]
I reproduce the bug by - get ready - quitting the Chrome browser and starting it again.

Watch: https://drive.google.com/file/d/0B4fNTUYL6CmdTnNNWjRydzFWMHc/view?usp=sharing

I delete the extension; I quit Chrome; I start it again and SourceKit magically re-appears in the list of Extensions. I could reproduce this on a 10-hour looping cycle. I need this Extension to disappear permanently. It popping up permissions notifications around 30-40 times today on two machines; no matter what sequence I use of deleting the Extension from this or that machine, in this or that order, with or without reboot (even at the OS level - Win7 64 & OSX 10.11.3), the Extension always reinstalls itself.

I wasted a solid hour today doing this.

Please. Help!

**Comment by nicknormal** [comment]
On the Chrome Web Store the URL of the extension has the following ID string:
iieeldjdihkpoapgipfkeoddjckopgjg

I was eventually able to locate a folder by this name in:
C:\Users\{username}\AppData\Local\Google\Chrome\User Data\BAK Default\Extensions

It was 4,296 files accounting for 18.5 MB of space; somehow the Extension was re-installing itself from this data, because upon deleting the folder the Extension no longer re-installs itself.

...

There was no extension folder by that ID string found on OSX, so somehow the Windows profile was passing data to Chrome cloud and re-inserting itself on OSX profile.

Weird!

I hope this helps others successfully uninstall this persistent extension.

**Comment by whatsdis** [comment]
people are leaving nasty reviews because of this bug

**Comment by kenotron** [comment]
I really can't fix this - this is Chrome Sync problem, no? It is overly aggressive in reinstalling stuff you removed.

**Comment by mcg** [comment]
First extension I've had to do this. Also when I do the "remove", Chrome never fully shutdown and I have to kill the process.

**Comment by nicknormal** [comment]
Not a Chrome Sync problem. Because if you disable Chrome Sync it still happens! It's a fault *with the extension* - only *this* extension! And my above "fix" didn't resolve; the folder re-appeared and the extension re-installed itself again tonight.

Please, man, work with Google, do what you have to do to resolve this; more bug reports will just keep filing in.

**Comment by kenotron** [comment]
Hmmm, the only thing I can find that would be related might be the external extension stuff that was maybe ... I'll try to publish another version without it...

**Comment by zenlc2000** [comment]
I have the same experience on OSX 10.10.5 with Chrome Version 51.0.2680.0 canary (64-bit). Every time I update the browser (~ daily) the extension asks for new permissions so I go delete it. Next day, same thing.

If this is a legitimate bug in a legitimate extension then I'm willing to wait / help find a solution. I just get nervous that this bug acts very malware-ish.

**Comment by urbanonymous** [comment]
Fun factor: I didnt install this app, installed some software and your malware-ish app started auto-installing on my chrome. Control+ Shift + N also fire the bug.

**Comment by whatsdis** [comment]
can you temporarily remove the extension or push empty code? That way, we will know for sure if this is caused by the extension or Google chrome. I already reported it to Google but here's hoping you can fix it from your end if possible. I know you worked hard on this and all but this is getting ridiculous.

**Comment by kenotron** [comment]
I did work hard on this but perhaps it is time to retire this

**Comment by kenotron** [comment]
This is unpublished. I'll keep it unpublished for a while. If it doesn't fix it, well I'm sorry I've tried :)

I've not followed the whole manifest file changes throughout the years because I don't spend much time on this project anymore. This is just a sad state: again, Google takes a perfectly open standard (the web) and make it totally closed (web store) with proprietary APIs. I don't see a real continuity between version upgrades in the manifest files. No thanks!

**Comment by kenotron** [comment]
> Fun factor: I didnt install this app, installed some software and your malware-ish app

Okay, THAT alone should clue you into the fact that *I* could not have made this "malware." I don't even know how that could even happen. How do you have an app installed without having the user install it? Wha? Anyway I reported this as a bug in here:

https://bugs.chromium.org/p/chromium/issues/detail?id=595592&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified#

**Comment by whatsdis** [comment]
thank you!
