### ISSUE TITLE
This is the end ? Broken link to Chrome Extensions Google Webstore

### ISSUE THREAD

**Issue by philippeko** [kenotron/sourcekit#123]
Hi guys,

Shall we close this project ? It was great initiative nethertheless <3

No **activity since a long time** and **broken link** to Chrome extensions Webstore ([This One](https://chrome.google.com/webstore/detail/iieeldjdihkpoapgipfkeoddjckopgjg)) sounds bad.

Kind regards,

--philippeko

**Comment by kenotron** [comment]
Unfortunately, when I've had a strong number of users complaining about how they cannot uninstall this app (besides, I think these web apps are being taken down actively). I don't see myself updating this on a platform that's going away. The only thing I might consider is if I RAN a service or created one on top of Electron. But wouldn't one just choose Visual Studio Code for that purpose?

**Comment by kenotron** [comment]
Closing this because it's closing time ? :)
